# Generated by Django 5.1.6 on 2025-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                ("foodId", models.AutoField(primary_key=True, serialize=False)),
                ("foodName", models.CharField(max_length=100)),
                ("foodtype", models.CharField(max_length=100)),
                ("foodCategory", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
