# Generated by Django 5.2 on 2025-04-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("Name", models.CharField(max_length=100)),
                (
                    "Email",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("Mobno", models.CharField(max_length=11)),
            ],
        ),
    ]
