# Generated by Django 5.2 on 2025-04-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="Email",
            field=models.CharField(max_length=100),
        ),
    ]
